#cloud-config

write_files:
  %{~ for f in files ~}
  - path: /var/app/${f.filename}
    permissions: %{ if substr(f.filename, -2, 2) == "sh"}0755%{else}0644%{endif}
    content: ${f.content}
    encoding: b64
  %{~ endfor ~}
  %{~ for c in docker_compose_files ~}
  - path: /etc/systemd/system/${coalesce(c.name, "app")}.service
    permissions: 0644
    content: |
      [Unit]
      Description=Docker Compose Service (${coalesce(c.name, "app")})
      Requires=docker.service ${join(" ", [ for f in docker_compose_files : "${f.name}.service" if f.name != null && c.name == null ])}
      After=docker.service

      [Service]
      Type=simple
      WorkingDirectory=/var/app
      Environment=HOME=/var/app TMP=/var/app/.tmp
      PassEnvironment=HOME TMP
      ExecStartPre=-/var/app/.bin/docker-compose -f ${c.filename} rm -f
      ExecStart=/var/app/.bin/docker-compose -f ${c.filename} up
      ExecStop=/var/app/.bin/docker-compose -f ${c.filename} stop -t 15
      ExecStopPost=-/var/app/.bin/docker-compose -f ${c.filename} rm -f

      [Install]
      WantedBy=multi-user.target

  %{~ endfor ~}
  - path: /etc/systemd/system/app-monitor.service
    permissions: 0644
    content: |
      [Unit]
      Description=Restart application

      [Service]
      Type=oneshot
      WorkingDirectory=/var/app
      Environment=HOME=/var/app TMP=/var/app/.tmp
      PassEnvironment=HOME TMP
      ExecStartPre=-/var/app/.bin/docker-compose pull --ignore-pull-failures
      ExecStart=/usr/bin/systemctl restart app.service

      [Install]
      WantedBy=multi-user.target

  - path: /etc/systemd/system/app-monitor.path
    permissions: 0644
    content: |
      [Unit]
      Description=Watch for updates to .env
      After=app.service

      [Path]
      PathChanged=/var/app/.env

      [Install]
      WantedBy=multi-user.target

runcmd:
  - set -x
  - mkdir -p /var/app/.bin
  - mkdir -p /var/app/.tmp
  - "[ $(docker network list -q --filter=name=web) ] || docker network create web"
  - |
    if [ ! -f /var/app/.bin/docker-compose ]; then
      curl --connect-timeout 20 --retry 3 --retry-delay 0 --retry-max-time 90 \
        -LJ "https://github.com/docker/compose/releases/download/1.26.1/docker-compose-$(uname -s)-$(uname -m)" \
        -o /var/app/.bin/docker-compose
      chmod +x /var/app/.bin/docker-compose
    fi
  - systemctl daemon-reload
  - systemctl enable --now app app-monitor.path
